import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createNativeBridge} from '../../china/native-bridge.mjs';
const tab={windowId:'one',tabId:'one',url:'https://www.zhipin.com/web/geek/jobs?query=AI'};
async function setup(t,replies,extra={}){const root=mkdtempSync(join(tmpdir(),'bridge-startup-'));t.after(()=>rmSync(root,{recursive:true,force:true}));let calls=0;const commands=[];const bridge=await createNativeBridge({root,session:{pid:123,...extra},startupTimeoutMs:30,pollMs:1,invokeNative:async(_bin,_args,input)=>{const a=JSON.parse(input);commands.push(a.command);calls++;return JSON.stringify(replies[Math.min(calls-1,replies.length-1)]);}});return{bridge,calls:()=>calls,commands};}
test('owned Chrome registration error -600 waits for its first tabs without navigation',async t=>{const f=await setup(t,[{errorCode:-600,processIdentity:'owned-start',tabs:[]},{errorCode:0,processIdentity:'owned-start',tabs:[tab]}]);assert.deepEqual(await f.bridge.tabs(),[tab]);assert.deepEqual(f.commands,['tabs','tabs']);});
test('an initially empty owned window list waits until Chrome creates the tab',async t=>{const f=await setup(t,[{errorCode:0,processIdentity:'owned-start',tabs:[]},{errorCode:0,processIdentity:'owned-start',tabs:[tab]}]);assert.deepEqual(await f.bridge.tabs(),[tab]);});
test('registration that never finishes is a bounded startup timeout, not a closed browser',async t=>{const f=await setup(t,[{errorCode:-600,processIdentity:'owned-start',tabs:[]}]);await assert.rejects(f.bridge.tabs(),e=>e.status==='browser_startup_timeout');assert(f.calls()<100);});
test('ownership failure cannot be retried as startup',async t=>{const f=await setup(t,[{errorCode:-1728}]);await assert.rejects(f.bridge.tabs(),e=>e.status==='browser_closed');assert.equal(f.calls(),1);});
test('automation denial cannot be retried as startup',async t=>{const f=await setup(t,[{errorCode:-1743,processIdentity:'owned-start'}]);await assert.rejects(f.bridge.tabs(),e=>e.status==='automation_permission_required');assert.equal(f.calls(),1);});
test('registration loss after the first successful tabs response remains terminal',async t=>{const f=await setup(t,[{errorCode:0,processIdentity:'owned-start',tabs:[tab]},{errorCode:-600,processIdentity:'owned-start',tabs:[]}]);await f.bridge.tabs();await assert.rejects(f.bridge.tabs(),e=>e.status==='browser_closed');assert.equal(f.calls(),2);});
test('a missing selection before JavaScript executes is retried once only after the same owned tab and URL reappear',async t=>{
 const ok={errorCode:0,processIdentity:'owned-start',tabs:[tab]},missing={errorCode:-1728,errorStage:'selected_tab_missing',processIdentity:'owned-start'};
 const f=await setup(t,[ok,missing,ok,{errorCode:0,processIdentity:'owned-start',result:'{"status":"ok"}'}]);
 await f.bridge.tabs();assert.deepEqual(await f.bridge.evaluate(tab,'read()'),{status:'ok'});assert.deepEqual(f.commands,['tabs','evaluate','tabs','evaluate']);
});
for(const changed of [[],[{...tab,tabId:'another'}],[{...tab,url:'https://www.zhipin.com/security.html'}]])test('missing selection with changed or absent tab remains stopped '+JSON.stringify(changed),async t=>{
 const f=await setup(t,[{errorCode:0,processIdentity:'owned-start',tabs:[tab]},{errorCode:-1728,errorStage:'selected_tab_missing',processIdentity:'owned-start'},{errorCode:0,processIdentity:'owned-start',tabs:changed}]);await f.bridge.tabs();await assert.rejects(f.bridge.evaluate(tab,'read()'),e=>e.status==='browser_closed');assert.deepEqual(f.commands,['tabs','evaluate','tabs']);
});
test('uncertain JavaScript failure never replays the operation',async t=>{const f=await setup(t,[{errorCode:0,processIdentity:'owned-start',tabs:[tab]},{errorCode:-1728,errorStage:'execute_javascript',processIdentity:'owned-start'}]);await f.bridge.tabs();await assert.rejects(f.bridge.evaluate(tab,'click()'));assert.deepEqual(f.commands,['tabs','evaluate']);});
test('selection recovery is bounded even if the same tab keeps vanishing',async t=>{const ok={errorCode:0,processIdentity:'owned-start',tabs:[tab]},missing={errorCode:-1728,errorStage:'selected_tab_missing',processIdentity:'owned-start'};const f=await setup(t,[ok,missing,ok,missing]);await f.bridge.tabs();await assert.rejects(f.bridge.evaluate(tab,'read()'));assert.deepEqual(f.commands,['tabs','evaluate','tabs','evaluate']);});
